@Platform.Gateway_HostAddress = http://localhost:5000
@BearerToken = your-access-token

GET {{Platform.Gateway_HostAddress}}/catalog/products
Authorization: Bearer {{BearerToken}}
Accept: application/json

###

GET {{Platform.Gateway_HostAddress}}/identity/users/me
Authorization: Bearer {{BearerToken}}
Accept: application/json

###
